### ISSUE TITLE
Consider alternative implementations for the offspring distribution

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/epichains#167]
I would remove this in favour of input checking whether `roffspring_name()` returns count values. Overall I think you should restrict which distributions users can sample from, or allow this to be a parameterised anonymous function as with {cfr}.

_Originally posted by @pratikunterwegs in https://github.com/epiverse-trace/epichains/pull/122#discussion_r1420157188_

**Comment by sbfnk** [comment]
The reason this can't be an anonymous function is that, where analytical solutions are available, we need to look up the corresponding likelihood function (either internally or provided by the user). See also the discussion in https://github.com/epiverse-trace/epichains/issues/25 and broader discussion in https://github.com/orgs/epiverse-trace/discussions/140

@pratikunterwegs if you had any ideas for how to handle this better it would be great to hear as I don't think the current solution requiring function lookups by name is a particularly satisfactory one.

**Comment by pratikunterwegs** [comment]
Thanks, I understand the issue better now. I guess the solution you have is very close to what I would implement; perhaps passing the function `rgamma` directly instead of a string (for a `do.call` this doesn't matter much, but can be useful if you want to check for the number of required arguments). IIRC the required arguments are being passed already as `...`. Restricting the functions to be among those for which you can access a log-likelihood should still work.

**Comment by sbfnk** [comment]
An option here that I hadn't considered is to do the lookup via the `substitute` function.

I.e. we could change the argument `offspring_dist` to take a function and then look up it's name, something like

``` r
test <- function(offspring_dist) {
  as.character(substitute(offspring_dist))
}

test(rpois)
#> [1] "rpois"
test(stats::rpois)
#> [1] "::"    "stats" "rpois"
test(function (x) { rpois() })
#> [1] "function"                    "as.pairlist(alist(x = ))"   
#> [3] "{\n    rpois()\n}"           "c(7, 6, 7, 29, 6, 29, 7, 7)"
```

<sup>Created on 2024-01-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

We could test for the last element of that character vector and if `== "rpois"` defer to `pois_size_ll()` and the like. I think this would retain all functionality we have at the moment.

**Comment by pratikunterwegs** [comment]
I guess that would work too but could be a little bit more work; alternatively, you could pop a note into the docs saying which functions are supported and break if the provided fn is not among them.

**Comment by sbfnk** [comment]
The key thing is that we need to do a lookup somehow, i.e. 
- user wants Poisson offspring -> we call `pois_size_ll()`
- user wants Negativ Binomial offspring -> we call `nbinom_size_ll()`
- user wants anything else -> we call `offspring_ll()`

**Comment by pratikunterwegs** [comment]
Using a simple `switch()`?

```r
fn_ll = switch(distr, rpois = pois_size_ll, nbinom = nbinom_size_ll, offspring_ll)
```

**Comment by sbfnk** [comment]
Not unless I'm missing something.

``` r
fn_ll <- function(distr) switch(distr, rpois = pois_size_ll, nbinom = nbinom_size_ll, offspring_ll)
fn_ll(rpois)
#> Error in switch(distr, rpois = pois_size_ll, nbinom = nbinom_size_ll, : EXPR must be a length 1 vector
```

<sup>Created on 2024-01-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by pratikunterwegs** [comment]
Ah, you'd need to quote the function name after all. Dummy fns for the LL used here.

``` r
fn_ll <- function(distr) {
  if (is.function(distr)) {
    distr = as.character(quote(distr))
  }
  switch(distr, rpois = rpois, nbinom = rnbinom, rnorm)
}

fn_ll("rpois")
#> function (n, lambda) 
#> .Call(C_rpois, n, lambda)
#> <bytecode: 0x11ceef9f8>
#> <environment: namespace:stats>
fn_ll(rpois)
#> function (n, mean = 0, sd = 1) 
#> .Call(C_rnorm, n, mean, sd)
#> <bytecode: 0x11e7d2e78>
#> <environment: namespace:stats>
fn_ll(rnbinom)
#> function (n, mean = 0, sd = 1) 
#> .Call(C_rnorm, n, mean, sd)
#> <bytecode: 0x11e7d2e78>
#> <environment: namespace:stats>
```

<sup>Created on 2024-01-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by sbfnk** [comment]
But they all return `stats::rnorm`? I think that's where you need `substitute()`, in which case we end up with my suggestion above.

**Comment by pratikunterwegs** [comment]
My mistake. I guess the options would then be to pass a string, or your solution.

**Comment by sbfnk** [comment]
Thanks for having a look and trying to come up with alternatives!
