### ISSUE TITLE
columns in return values of `simulate_tree`

### ISSUE THREAD

**Issue by sbfnk** [epiverse-trace/epichains#175]
I think the names of the columns in `simulate_tree` and their documentation could be improved.

Especially:
- `infectee_id` tracks which of the index cases is the root of each infectee. Perhaps call it `index_case_id`?
- `sim_id` gives a unique id to each infectee that linked to a given index case (such that the combination of `index_case` and `sim_id` is unique. Should this perhaps not be called `infectee_id`? And be unique throughout the data frame (rather than unique for each index case)?

I'm also wondering if `_id` really needs to be added to the column names or whether they could just be `index_case`, `infectee`, `infector`.

So instead of currently something like
```{r}
+   infectee_id sim_id infector_id generation time
1            1      1          NA          1    0
2            2      1          NA          1    0
3            3      1          NA          1    0
4            1      2           1          2    3
5            2      2           1          2    3
6            3      2           1          2    3
7            1      3           1          2    3
8            2      3           1          2    3
9            3      3           1          2    3
```

one would have something like 
```{r}
+   index_case infectee infector generation time
1            1       1       NA          1    0
2            2       2       NA          1    0
3            3       3       NA          1    0
4            1       4        1          2    3
5            2       5        2          2    3
6            3       6        3          2    3
7            1       7        1          2    3
8            2       8        2          2    3
9            3       9        3          2    3
```

**Comment by jamesmbaazam** [comment]
Closing as completed in #242.
