### ISSUE TITLE
Recent PRs #171 and #182 could do with a news item

### ISSUE THREAD

**Issue by sbfnk** [epiverse-trace/epichains#189]
Recent PRs #171 and #182 deprecated some functions and added a new one which, I think, should be accompanied by a news item

**Comment by jamesmbaazam** [comment]
Thanks. I've not been adding NEWS items because the package has not yet been released and the purpose of the NEWS/changelog, I think, is to inform the users of changes between versions?

**Comment by sbfnk** [comment]
Yes, that makes sense. We should probably flag if we add major new features vs. bpmodels but perhaps for the recent PRs it isn’t strictly needed.

**Comment by jamesmbaazam** [comment]
Yes, so the plan is to write a NEWS file for the v0.1.0 release that introduces the features of {epichains} and as you say, compare them with bpmodels and "convince" users to prefer {epichains}.
