### ISSUE TITLE
Should `summary()` report infinite outbreaks as max?

### ISSUE THREAD

**Issue by sbfnk** [epiverse-trace/epichains#239]
Perhaps just me but I find this a bit confusing. Should the `Max` not be `Inf`?

``` r
library("epichains")

set.seed(1)
chains_pois_offspring <- simulate_chains(
  index_cases = 3,
  statistic = "size",
  offspring_dist = rpois,
  stat_max = 10,
  lambda = 1
)
chains_pois_offspring |>
summary()
#> `epichains_summary` object 
#> 
#> [1]   1 Inf   2
#> 
#>  Simulated tree sizes: 
#> 
#> Max: 2
#> Min: 1
```

<sup>Created on 2024-03-26 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by sbfnk** [comment]
Perhaps report it as `>=10` if `stat_max` is 10 etc.?

**Comment by jamesmbaazam** [comment]
That's a solution but it would make the values a string 😬 .

**Comment by sbfnk** [comment]
But the max/min aren't returned (only printed), or are they?

**Comment by jamesmbaazam** [comment]
The values are gotten from `summary()` and then formatted for printing. The nice thing about keeping the parameters as attributes is that, we can let summary return `Inf` if it's the max, and in the formatting step, replace `Inf` with `>=stat_max`.

**Comment by sbfnk** [comment]
Yep that sounds like a great solution.
