### ISSUE TITLE
allow `offspring` argument to be a function

### ISSUE THREAD

**Issue by pearsonca** [epiverse-trace/epichains#25]
the `offspring` argument to `chain_sim` should support passing a function of n (like `serial` argument).

**Comment by sbfnk** [comment]
> so people would need to provide both the sampling and likelihood functions (potentially - probably someway to introspect some common ones) - that seems plausibly doable, if there's demand?

Instead of requiring that, and in the spirit of what I understand to be the underlying issue (`offspring` and `serial` calling for different approaches), how about changing `serial` to take a character string (with corresponding random and distribution functions expected to be present in the environment)? My sense is that this would be simpler.

**Comment by pearsonca** [comment]
sure, but: why not both? R is pretty good at introspection.

could approach as
 - have some internal infrastructure to check for a string
 - if a string, promote to the function version; otherwise use argument as the function
 - then have the rest of internal code work always work with the function version

**Comment by sbfnk** [comment]
Yes, could do, though it would require some overhead as some function access the `r` version, some the `d` version, some both - so we'd need to pass either one or either of them.

We could define a distribution S3 object which has optional `sample`, `density` etc. containers. Would you say the benefit from doing so is worth the additional overhead (or have a better idea)?

**Comment by sbfnk** [comment]
See also discussion at https://github.com/epiverse-trace/epichains/pull/33#issuecomment-1600741651 which I'll continue here

**Comment by sbfnk** [comment]
An additional issue with a lambda approach is that it precludes the lookup for analytical likelihoods included with the package.
