### ISSUE TITLE
Rename current functions

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/epichains#26]
The current function names could be improved as part of the new package infrastructure. I am going to suggest the following and welcome suggestions to refine them:

- [ ] `chain_sim()` -> `simulate_chains()`
- [ ] `chain_ll()` -> `estimate_loglikelihood()`
- [ ] `chain_sim_susc()` should be a subtype of `simulate_chains()`

**Comment by sbfnk** [comment]
A possible would be `estimate_likelihood` with a `log` argument as suggested in https://github.com/epiverse-trace/bpmodels/issues/73

**Comment by jamesmbaazam** [comment]
Agreed! I'll make the change.

**Comment by jamesmbaazam** [comment]
> A possible would be `estimate_likelihood` with a `log` argument as suggested in [epiverse-trace#73](https://github.com/epiverse-trace/bpmodels/issues/73)

Alternatively `estimate_chain_likelihood()`.

**Comment by sbfnk** [comment]
> Alternatively `estimate_chain_likelihood().`

I think given that we now have `chain` in the package name I think we should be fine with the shorter name, i.e. one could call `epichains::estimate_likelihood`.

**Comment by jamesmbaazam** [comment]
Agreed. Let's go with `estimate_likelihood()` for now and solicit user feedback.
