### ISSUE TITLE
Implement interventions in models

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/epichains#3]
The current models do not include interventions. A necessary enhancement will be the inclusion of interventions in the model setup.

## Conceptualisation

The interventions will impact how offspring are produced. This can be implemented as a reduction in $R_0$, some kind of "pruning" of connections, or a re-specification of the offspring and serial interval distribution to impact the number of offspring produced. 

As an example, in the paper, ["The impact of travel restrictions on COVID-19 cases in Hong Kong"](https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-021-11889-0), the offspring distribution is specified as a conditional Poisson distribution with a mean that depends on physical distancing, the number of susceptible individuals in the population, the type of infection the infected individual has (asymptomatic, pre-clinical or clinical), and the number of days since the date of infection.

## Implementation

We will implement generic interventions that:

- [x] Scale $R0$
- [ ] Truncate the offspring distribution
- [ ] Truncate the serial distribution

## Literature

The following papers provide branching process models that include non-pharmaceutical interventions. 

Non-pharmaceutical interventions:

* _Scalar reduction in transmission at the individual and population level_ [Superspreading and the effect of individual variation on disease emergence](https://www.nature.com/articles/nature04153)
* NPIs targetted at the whole population, randomly selected individuals, and targetted individuals as described in Appendix B of the paper, ["The effect of superspreading on epidemic outbreak size distributions"](https://www.sciencedirect.com/science/article/pii/S0022519308001124?casa_token=1Dip2yv4DX8AAAAA:ydLFfqNZvNQoHMWK-BjttjeYLj5o-ZzCWiTbe6A0iH3F192Xe4WbuHPVaoEMxyXjLqTE0kk#sec4). The paper also clearly outlines the model modifications required to achieve this. In most cases, given an intervention efficacy of $c$ where $0 \le c \le 1$, the $R_0$ of the affected subset of the population will become $(1-c)R_0$ when the intervention is in place.
* _Contact tracing_: [Implication of backward contact tracing in the presence of overdispersed transmission in COVID-19 outbreaks](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7610176/)
* _Travel/movement restriction_: [Modelling the impact of travel restrictions on COVID-19 cases in Hong Kong in early 2020](https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-021-11889-0)
* _Isolation_: [Feasibility of controlling COVID-19 outbreaks by isolation of cases and contacts](https://www.thelancet.com/article/S2214-109X(20)30074-7/fulltext)
    - Note that this paper's code has been bundled up into the [ringbp](https://github.com/epiforecasts/ringbp) R package.
 *  _Isolation_: [Using a real-world network to model localised COVID-19 control strategies](https://github.com/jamesmbaazam/covidhm) 

Vaccination:

* [SIR epidemics and vaccination on random graphs with clustering](https://link.springer.com/article/10.1007/s00285-019-01347-2#Sec15)

Other papers to consider:

* [Different epidemic curves for Severe Acute Respiratory Syndrome reveal similar impacts of control measures](https://academic.oup.com/aje/article/160/6/509/79472)
* [Dimensions of superspreading](https://www.nature.com/articles/438293a)
* [The construction and analysis of epidemic trees with reference to the 2001 UK foot-and-mouth outbreak](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1691228/)

**Comment by sbfnk** [comment]
One simple option would be to support truncating either the serial interval or the offspring distribution using the `truncdist` package, which is already imported for modelling susceptible depletion, and which supports the same syntax as used here in specifying random distributions by a character string (see also related discussion in #25).

**Comment by sbfnk** [comment]
The other thing that could be done would be the implementation of a reduction in transmission, i.e. the `c` from the [supplementary notes of Lloyd-Smith et al., 2005, section 2.5.3](https://static-content.springer.com/esm/art%3A10.1038%2Fnature04153/MediaObjects/41586_2005_BFnature04153_MOESM1_ESM.pdf). 

@joshwlambert this could then be used to simulate individual-specific vs population-wide control, as in Fig. 3c of that paper.

**Comment by joshwlambert** [comment]
@sbfnk @jamesmbaazam The use of  the individual-level and population-level controls (`c`, from Lloyd-Smith et al.) would be useful. I'm currently working on exactly that for {superspreading} (see epiverse-trace/superspreading#13). 

I'm using {bpmodels} for the simulation, but would be happy to move to using {epichains} if these features were included.

**Comment by jamesmbaazam** [comment]
Some good discussions here. @joshwlambert please go ahead with {bpmodels} for now. 

And just as we've done in the past with other vignettes, if new features/packages become available, the vignettes can either be modified to use them or compare the old and new. Both alternatives are useful for the user in my opinion.

**Comment by sbfnk** [comment]
To be superseded by #103

**Comment by jamesmbaazam** [comment]
After some internal discussions, we agreed not to implement the intervention mechanism in this package but rather in the [epidemics](https://github.com/epiverse-trace/epidemics) package, so this issue has been partly addressed here with the vignette in #106 will be closed.

**Comment by pratikunterwegs** [comment]
Hi, coming in here from the full package review #122 - I completely missed this exchange when it happened. Could you please include me when discussing developments related to {epidemics} and modelling generally? I would disagree substantially with the previous comment and especially the idea interventions would only be implemented in {epidemics}.

As far as I can recall, we agreed to see how interventions could be harmonised across the packages - having looked into {epichains} a bit more, I'm still not convinced that there should be deep technical harmonisation (i.e., shared classes, interdependency, etc.) - which makes it a bit odd that a whole feature has been considered necessary in this package, has been added, and then removed, without substantial discussion as to the pros and cons.

**Comment by jamesmbaazam** [comment]
> Hi, coming in here from the full package review #122 - I completely missed this exchange when it happened. Could you please include me when discussing developments related to {epidemics} and modelling generally? I would disagree substantially with the previous comment and especially the idea interventions would only be implemented in {epidemics}.

You weren't excluded. A long conversation happened on Slack before this decision was taken. We can revert the decision in the new year following major updates to the functionality here in response to #122. We will include you in the discussion then. 

> As far as I can recall, we agreed to see how interventions could be harmonised across the packages - having looked into {epichains} a bit more, I'm still not convinced that there should be deep technical harmonisation (i.e., shared classes, interdependency, etc.) - which makes it a bit odd that a whole feature has been considered necessary in this package, has been added, and then removed, without substantial discussion as to the pros and cons.

There was substantial discussion.

**Comment by pratikunterwegs** [comment]
Hi James, just to gently point out that this seems to have been on the epichains channel, where I haven't joined. I don't mind the direction in which you take the package, and I'm happy for there to be one or multiple implementations of interventions, depending on what seems best for Epiverse needs - I am not opposed to interventions coming in in epichains as well, although this issue now appears to be superseded.
