### ISSUE TITLE
Consider S3 output class for `chain_ll()` and `chain_sim()`

### ISSUE THREAD

**Issue by joshwlambert** [epiverse-trace/epichains#4]
In the README, the different output of `chain_ll()` depending on `nsim_obs` and and the use of `summary()` mean you could make an S3 class to provide a consistent return type. It would also allow you to write a custom `summary()` method to show information you think is important.

For `chain_sim()` the return type varies depending on the `tree` argument. The use of S3 would also benefit any future work on custom `print()` methods. 

This issue is not meant as a suggestion, but rather an idea for consideration.

**Comment by jamesmbaazam** [comment]
This is currently a work in progress and will soon be submitted as a PR. `chain_sim()` has been split into two functions to remove the complex interaction between the `tree` and `serial` arguments. The resulting functions return `epichains` objects with attributes that allow dedicated `print`, `summary` and `plot` method dispatches.
