### ISSUE TITLE
Package name not rendering in README 

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/epichains#52]
Ensure the `{{ packagename }}` variable in the README picks and renders the package name.

**Comment by jamesmbaazam** [comment]
@Bisaloo Could you help me diagnose this? The `render-readme` workflow seems fine to me.

**Comment by Bisaloo** [comment]
Yes, I confirm the `render-readme` workflow is correct. The unrendered string seems to come from a manual README render (https://github.com/epiverse-trace/epichains/commit/291aa29751fc329f69a78b9aea063636d8361deb), where `knit_expand()` was likely not run.

This is the downside of this automated approach: you need one extra step to render it locally.

https://github.com/epiverse-trace/packagetemplate/commit/dc505de6287888ab1e7b9cf75a54b69d1a4c9f76 added instructions on how to reproduce the workflows' behaviour locally.

**Comment by Bisaloo** [comment]
An alternative approach could be to put this code inside the rmarkdown file :thinking:
