### ISSUE TITLE
Restructure `<epichains>` and `<epichains_aggregate_df>` classes

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/epichains#79]
This PR is mostly adding tests, but one issue that I noticed is that `<epichain>` and `<epichains_aggregated_df>` objects can inherit from different base classes (data.frame and vector, and data.frame and list, respectively). I'm not sure whether it's a good idea to get into conditional inheritance in this way. This would probably make it difficult for future developers to easily account for what sort of object a function will return. If the data in each case (e.g. epichain_tree vs epichain_summary) is sufficiently different, perhaps it would be better to have separate classes. If you would find an overarching signature more convenient for some methods, the existing classes could be defined as abstract super-classes with sub-classes instead. Happy to discuss this further.

_Originally posted by @pratikunterwegs in https://github.com/epiverse-trace/epichains/pull/71#pullrequestreview-1632950288_
   
This issue will be addressed with a PR to:
- [ ] Remove option to return aggregations by both time and generation as it returns an `<epichains_aggregate_df>` that inherits from `<list>` while aggregations by either time or generation return a <data.frame> subclass. Associated issues: #81
- [ ] Refactor `simulate_summary()` to return an `<epichains_summary>` class. However, this name is likely to be confused with the `summary()` method and needs some consideration. This will involve:
    - [ ]  Setting up constructors, validators, and helpers for the `<epichains_summary>` class 
    - [ ] Tests for the new class
- [ ] Refactor `simulate_tree()` and `simulate_tree_from_pop()` to return an `<epichains_tree>` object. This will involve:
    - [ ] Setting up constructors, validators, and helpers for the `<epichains_tree>` class
    - [ ] Tests for the new class

**Comment by pratikunterwegs** [comment]
When you tackle this issue, would it be possible to define a `summary.epichain()` method that returns an `<epichain_summary>? That seems like it might be more user friendly.

**Comment by jamesmbaazam** [comment]
Changes are being made in the linked PR. Reviews will be welcome.
