### ISSUE TITLE
Column names in `epichains` data.frame returned by `simulate.tree`

### ISSUE THREAD

**Issue by sbfnk** [epiverse-trace/epichains#92]
Some of the current column names (`chains_id` and `sim_id`) aren't very intuitive. Would they perhaps be better as, say, `tree` and `individual`?

**Comment by jamesmbaazam** [comment]
This is a good point. I'm actually thinking doing `ancestor` -> `infector` and `chain_id` -> `infectee`? This is also based on user feedback from @CarmenTamayo.
